Update GetQRCode.ashx.cs to allow RGBA values
SparkDevNetwork/Rock pull request #5989
Opened 2024-08-20 23:14 UTC by nlBayside

## Proposed Changes
https://community.rockrms.com/ideas/2009/allow-customizable-colors-for-qr-codes

This change allows for RGBA hex values in the QR Code generator. These values can come in as RRGGBB, or RRGGBBAA hex values.

## Types of changes

What types of changes does your code introduce to Rock?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality, which has been approved by the core team)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x ] This is a single-commit PR. (If not, please squash your commit and re-submit it.)
- [ x] I verified my PR does not include whitespace/formatting changes -- because if it does it will be closed without merging.	
- [ x] I have read the [Contributing to Rock](https://github.com/SparkDevNetwork/Rock/blob/master/.github/CONTRIBUTING.md) doc
- [x ] By contributing code, I agree to license my contribution under the [Rock Community License Agreement](https://www.rockrms.com/license)
- [ x] Unit tests pass locally with my changes
- [ x] I have added any required [unit tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.UnitTests/README.md) or [integration tests](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Tests.Integration/README.md) that prove my fix is effective or that my feature works
- [ x] I have included updated language for the [Rock Documentation](https://www.rockrms.com/Learn/Documentation) (if appropriate)

## Further comments
I made these changes with 6 and 8 digit RGBA values in mind, not 3 or 4-length values (like CSS allows). If that is something people would also like to see in the change, I can accommodate that. I think it would be useful to incorporate the RockColor utilities class into this because it has a Dictionary of CSS hex values and their keywords.

The only downside of that is that you still need to convert the hex values into a `byte[]` because of QRCoder's method overloads.

## Documentation
New documentation should be applied once these changes are made so that users understand the flexibility they now have when creating QR codes.

2024-08-21 21:41 UTC, nairdo requested changes
Thanks Noah.  Can you check out these small adjustments?  Let me know if you have any questions/concerns.

2024-08-21 21:41 UTC, nairdo commented on RockWeb/App_Code/GetQRCode.ashx.cs
> +        private byte[] HexToByteArray( string hex )
FYI: We'll be minimally adding a small section next to this section in the Developer 101 guide around here: 
https://community.rockrms.com/developer/book/16/16/content#referencingfilesandimages

2024-08-22 15:24 UTC, nairdo commented on RockWeb/App_Code/GetQRCode.ashx.cs
> +        private byte[] HexToByteArray( string hex )
@nlBayside Also check the foreground and background colors when used with SVG vs PNG.  I think you might have one of them reversed.

2024-08-26 20:41 UTC, nlBayside commented
Let me know if those changes suffice! I had it done in the browser editor. So if I missed something I can go back and fix that

2024-08-28 16:29 UTC, merged